title: Site

fields:
  siteName:
    label: Site Name
    type: text

  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  email:
    label: Email
    type:  email
    width: 1/2

  telephone:
    label: Telephone
    type: text
    width: 1/2

  description:
    label: Description
    type:  textarea

  topBarText:
    label: Top Bar Text
    type: text

  headerSubtitle:
    label: Header Subtitle
    type: text
    width: 1/2

  footerSubtitle:
    label: Footer Subtitle
    type: text
    width: 1/2

  lowtechhighfuture:
    label: Low Tech, High Future →
    type: text
    
  copyright:
    label: Copyright
    type:  text

  headquartersTitle:
    label: Headquarters Title
    type: text
    width: 1/3

  officeTitle:
    label: Office Title
    type: text
    width: 1/3

  telephoneTitle:
    label: Telephone Title
    type: text
    width: 1/3

  emailTitle:
    label: Email Title
    type: text
    width: 1/3

  socialTitle:
    label: Social Networks Title
    type: text
    width: 1/3

  legalTitle:
    label: Legal Notice Title
    type: text
    width: 1/3

  headquartersAddress:
    label: Headquarters Address
    type: textarea
    width: 1/2

  officeAddress:
    label: Office Address
    type: textarea
    width: 1/2

  twitter:
    label: Twitter
    type: text
    width: 1/2

  linkedin:
    label: LinkedIn
    type: text
    width: 1/2
